### PR TITLE
Update Python versions

### PR DESCRIPTION
**Pull request by miketheman**
New versions of supported Python runtimes released recently: https://pythoninsider.blogspot.com/2023/08/python-3115-31013-3918-and-3818-is-now.html

### CODE REVIEW

**Comment by humitos** [comment]
Thanks! We will need a PR similar to https://github.com/readthedocs/readthedocs.org/pull/10217 to be able to merge this one.

**Comment by miketheman** [comment]
@humitos do they have to go at the same time? I thought this builder had to be completed before the other repo gets updated to use these images.

**Comment by miketheman** [comment]
Added https://github.com/readthedocs/readthedocs.org/pull/10721

**Comment by ThiefMaster** [comment]
3.11.6 is out, also 3.12.0 has been released - would be nice to include that as well!

**Review by humitos — APPROVED** [review]
Thanks!

**Pull request merged**
