### PR TITLE
Upload new build tools

### PR DESCRIPTION
**Pull request by stsewd**
Ref https://github.com/readthedocs/readthedocs.org/pull/9268

### CODE REVIEW

**Review by humitos — APPROVED** [review]
I hope this works and upload everything automatically when merged to `main` 🤞🏼 

We should be ready to QA on production (both cloud) after merging and uploading the new versions, just in case. Note that merging this PR **deploys the new versions to production**

**Comment by stsewd** [comment]
@humitos this doesn't remove the existing ones, right?

**Comment by stsewd** [comment]
Reading https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html you need to pass `--delete` for that to happen, so looks like it won't delete existing files.

**Review by agjohnson — APPROVED** [review]

**Comment by agjohnson** [comment]
Should we wait to merge this on release day? Or I suppose line it up so everything is ready as we start release?

**Comment by humitos** [comment]
@stsewd 

> @humitos this doesn't remove the existing ones, right?

No, it will override the existing ones with the new ones just built.

@agjohnson 

> Should we wait to merge this on release day? Or I suppose line it up so everything is ready as we start release?

I think merging this PR during release is the best, so we are all watching this in case we need to take some action.

**Comment by humitos** [comment]
BTW, we need to make the tests to pass to be able to merge this PR because otherwise, it won't upload anything to S3 😄

**Comment by stsewd** [comment]
Tests seem to have been failing since March

**Pull request merged**
