### PR TITLE
Update Rust to 1.52.0

### PR DESCRIPTION
**Pull request by Daggy1234**
As mentioned in my issue #169 I have bumped rust version for master

### CODE REVIEW

**Review by stsewd — APPROVED** [review]
Thanks

**Comment by astrojuanlu** [comment]
Just so I understand, are the Travis CI failures expected?

**Comment by stsewd** [comment]
> Just so I understand, are the Travis CI failures expected?

We should fix those, but they aren't related to this change

**Review by humitos — CHANGES_REQUESTED** [review]
I don't think we should merge this PR. Merging it won't upgrade the version on the Docker images for users. It's a false sensation of moving forward when the upgrade is not really happening.

It will just add more differences between 7.0, 8.0, and master versions without _real_ progress 😄 

These images should be frozen until we implement the design doc we wrote and we build & publish the new images. See my comment at https://github.com/readthedocs/readthedocs-docker-images/issues/169#issuecomment-856612051 and the design doc at https://docs.readthedocs.io/en/stable/development/design/build-images.html

**Comment by Daggy1234** [comment]
@humitos those don't work



idk why

**Comment by humitos** [comment]
> I must not have access to those images

Yes, they are not available yet. The document that I linked is not already implemented.

> What realistic solution could I use to compile a rust-python package with rust1.52+

Unfortunately, we don't have a good way to do this currently. You could try to hack something in your `conf.py` to download and install Rust as a workaround on each build, but I'm not sure if that will work either.

**Comment by humitos** [comment]
Hi @Daggy1234! In #166 we implemented the ability to install rust 1.55.0 --which is still in beta. Would you like to give it a try and let us know if it works? You need to add something like this to your `.readthedocs.yaml` file:

```yaml
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
    rust: "1.55"
```

**Comment by Daggy1234** [comment]
oh thats awesome!

**Pull request closed without merging**
